### ISSUE TITLE
Exit button gone

### ISSUE THREAD

**Issue by Hanifinio** [Weebifying/restartbutton-geode#1]
I had the exit button before but now it's gone despite still being toggled on. It's probably happening because of another mod like BettterMenu or Geometry Dash but those didn't change anything enabled or disabled.  
     I'm on Android btw
![Screenshot_20240311_061917_Geode](https://github.com/Weebifying/restartbutton-geode/assets/162050629/f24410e4-4b48-4f1e-8f41-0e4abed4c159)

**Comment by Weebifying** [comment]
minecraft menu removed that button, will fix later

**Comment by Weebifying** [comment]
minecraft menu removed the exit button lmao

**Comment by Weebifying** [comment]
also i just realized theres a quit game button already LOL
![image](https://github.com/Weebifying/restartbutton-geode/assets/70783792/103fa403-bb37-4ab2-924e-d4aa8ec72703)
