### ISSUE TITLE
Restart button not working properly

### ISSUE THREAD

**Issue by LukaTV939** [Weebifying/restartbutton-geode#2]
Whenever I restart through the restart button on this mod and from there only I constantly get these error messages:
![image](https://github.com/Weebifying/restartbutton-geode/assets/55237683/ce4e8fda-7ee5-44b6-9343-2881f6f1a7ae)
![image](https://github.com/Weebifying/restartbutton-geode/assets/55237683/9ff12342-e9a9-4fac-b8d4-ef5046fa5bdd)

It's fine when I restart through the geode menu when updating and uninstalling a mod, but not for this, and I also don't get any crash logs.

**Comment by Weebifying** [comment]
fixed!!
